[2024-06-24T11:54:23.371+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T11:54:23.391+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2024-06-24T04:54:15.608589+00:00 [queued]>
[2024-06-24T11:54:23.400+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2024-06-24T04:54:15.608589+00:00 [queued]>
[2024-06-24T11:54:23.401+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T11:54:23.412+0700] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-06-24 04:54:15.608589+00:00
[2024-06-24T11:54:23.418+0700] {standard_task_runner.py:63} INFO - Started process 31771 to run task
[2024-06-24T11:54:23.421+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-06-24T04:54:15.608589+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5e_15us7']
[2024-06-24T11:54:23.422+0700] {standard_task_runner.py:91} INFO - Job 17: Subtask is_api_available
[2024-06-24T11:54:23.485+0700] {task_command.py:426} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-06-24T04:54:15.608589+00:00 [running]> on host daniel
[2024-06-24T11:54:23.576+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T04:54:15.608589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T04:54:15.608589+00:00'
[2024-06-24T11:54:23.578+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T11:54:23.578+0700] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-24T11:54:23.578+0700] {http.py:137} INFO - Poking: api/
[2024-06-24T11:54:23.592+0700] {base.py:84} INFO - Using connection ID 'user_api' for task execution.
[2024-06-24T11:54:24.118+0700] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-24T11:54:24.119+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T11:54:24.133+0700] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=manual__2024-06-24T04:54:15.608589+00:00, execution_date=20240624T045415, start_date=20240624T045423, end_date=20240624T045424
[2024-06-24T11:54:24.168+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T11:54:24.188+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T11:54:24.189+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
